### ISSUE TITLE
error in 1.1.1

### ISSUE THREAD

**Issue by flexoo** [Wyrrrd/Gun_Turret_Alerts#1]
Crashed a few secs after loading save.

![error](https://user-images.githubusercontent.com/13826740/112757265-8743af80-8fd8-11eb-9e5d-91487344a3b3.png)

**Comment by Wyrrrd** [comment]
Thanks for the report, fixed in [1.1.2](https://github.com/Wyrrrd/Gun_Turret_Alerts/releases/tag/v1.1.2)
