### ISSUE TITLE
I have no arrow

### ISSUE THREAD

**Issue by d0ob** [Wyrrrd/Gun_Turret_Alerts#4]
Hi there ! 

It's not always the most practical to locate the concerned entity, could it be doable to add arrows, as in other alerts ? (Well, there isn't right ? ^^ I have none at least.) 

Alos, I saw the request for trad in description, and no french file here, could be of any use ? While I'm here I did one anyway ; Maybe some sentences are a bit long, french can be talkative, I still tried to be concise, but I could make smaller if needed. I'll paste down here.

Thanks ! Regards.

**Comment by d0ob** [comment]
[mod-setting-name]
gun-turret-alerts-enabled=Activer les alertes de manque de munitions dans les tourelles.
gun-turret-alerts-car-enabled=Activer les alertes de manque de munitions dans les véhicules.
gun-turret-alerts-mode=Prendre en considération plusieurs compartiments de munitions.
gun-turret-alerts-threshold=Nombre de munitions restantes avant d'être alerté.

[mod-setting-description]
gun-turret-alerts-enabled=Le manque de munitions dans une tourelle enverra une alerte au joueur.
gun-turret-alerts-car-enabled=Le manque de munitions dans un véhicule enverra une alerte au joueur.
gun-turret-alerts-mode=Surveiller tous les compartiments de l'unité, un seul, ou une sélection.\n(Certaines unités, principalement des véhicules, peuvent posséder plusieurs compartiments. À laisser décoché s'il n'y en a qu'un seul.)
gun-turret-alerts-threshold=Le nombre de munitions, dans une tourelle ou un véhicule, qui déclenchera un alerte une fois atteint.

[string-mod-setting]
autofilter_mode-added=Tous
autofilter_mode-individually=Unique
autofilter_mode-selected=Sélection

[gun-turret-alerts]
message-empty=__1__ Plus de munition
message-low=__1__ Peu de munitions

[virtual-signal-name]
ammo-icon-red=Signal d'absence de munition
ammo-icon-yellow=Signal de manque de munitions

**Comment by Wyrrrd** [comment]
As far as I know, arrows on custom (modded) alerts are not possible as of now. If you somehow find another mod doing this, feel free to reopen the issue and post a link to it.

(Also, I will add your translation to the next release, thanks a lot!)

**Comment by d0ob** [comment]
No indeed, now you say it, it is all vanilla alerts. So that's why there is no arrow, I was wondering why not while it would be much more practical, I should have thought of the possibility that it's simply not doable... ^^ Arf, one more thing the base game is working on I hope !

But anyway, thanks for your quick answer, and for the mod too ! 
Cause I forgot to tell the obvious in previous message, I should have : I love the mod ! Already more than usefull as it is ! 

PS: Now I slept a bit, I found some misstakes in my translation so I'll edit it ^^ Sorry for that, shouldn't be any anymore !

**Comment by Wyrrrd** [comment]
Translation is now released. I'd be happy if you would consider adding locales to my other mods, too.

**Comment by d0ob** [comment]
I can do that ! And would be happy too, I liked doing it ^^
_I don't know how to pull a request tho, I open an issue under each, or post it down here ?_ 
I think I found out ! I'll try (well, not sure... lol)

And since I just learned from my first translation that re-reading the next day is usefull ^^ I'll post only when certain, better be cautious ! 

Edit: I installed a french version of the game to look at legit words, I took the occation to try the ammo alert translation, there is kindof an issue : The selection setting, about ammo spaces, it stay in english, (the drop down box "added, individually, selected") So, if it's supposed to be that way, I should maybe add the english terms to the tooltip !

**Comment by Wyrrrd** [comment]
My preference would be to get it as a pull request. I'd like to reserve issues for feature requests and bug reports. If you want to get into this, you might want to first start to read about forks, then continue [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). I use Github Desktop for the git part, gives you a nice frontend for it.

If you don't, then I gladly take input in [this thread](https://mods.factorio.com/mod/Gun_Turret_Alerts/discussion/610e8864c4e883b1631e14e0) on the factorio mod page.

(I'd also rather continue there, so we don't bloat this issue, which was initially about arrows :P )
