### ISSUE TITLE
poor interaction of mods

### ISSUE THREAD

**Issue by Vektor-537** [Wyrrrd/Gun_Turret_Alerts#5]
poor interaction of mod [Renai Transportation](https://mods.factorio.com/mod/RenaiTransportation)
Renai Transportation adds jumping platforms for trains, including trampolines on which trains can jump forever. while they are jumping, they do not need fuel and cannot be refueled in conventional ways.

**Comment by Wyrrrd** [comment]
How does this relate to Ammo Alerts, which sends alerts for low ammunition, what is the interaction at all?
